#!/usr/bin/env python3
import rospy

from spot_driver.dual_spot_utils.tf_compute_graphnav import MultiSpotTransformPublisher

if __name__ == "__main__":
    rospy.init_node('spot_tf_compute')
    publisher = MultiSpotTransformPublisher()
    rospy.spin()  # Let ROS handle the callbacks
